APOLLO_LEADS = [
    {
        "id": "apollo-001",
        "name": "Sarah Chen",
        "company": "Meridian Health Group",
        "title": "Head of Digital Transformation",
        "email": "s.chen@meridianhealth.com.au",
        "source": "apollo",
        "industry": "healthcare",
        "company_size": 450,
        "is_authentic": True,
    },
    {
        "id": "apollo-002",
        "name": "James Worthington",
        "company": "FinEdge Capital",
        "title": "CTO",
        "email": "j.worthington@finedge.com.au",
        "source": "apollo",
        "industry": "fintech",
        "company_size": 120,
        "is_authentic": True,
    },
    {
        "id": "apollo-003",
        "name": "Priya Sharma",
        "company": "LearnPath Education",
        "title": "Operations Manager",
        "email": "priya@learnpath.edu.au",
        "source": "apollo",
        "industry": "education",
        "company_size": 85,
        "is_authentic": True,
    },
    {
        "id": "apollo-004",
        "name": "Tom Bradley",
        "company": "Bradley's Bakery",
        "title": "Owner",
        "email": "tom@bradleysbakery.com.au",
        "source": "apollo",
        "industry": "food_retail",
        "company_size": 12,
        "is_authentic": True,
    },
    {
        "id": "apollo-005",
        "name": "Fake Contact",
        "company": "Nonexistent Corp",
        "title": "CEO",
        "email": "",
        "source": "apollo",
        "industry": "saas",
        "company_size": 500,
        "is_authentic": False,
    },
    {
        "id": "apollo-006",
        "name": "David Liu",
        "company": "CloudSync Solutions",
        "title": "VP Engineering",
        "email": "david.liu@cloudsync.io",
        "source": "apollo",
        "industry": "saas",
        "company_size": 230,
        "is_authentic": True,
    },
]

LINKEDIN_LEADS = [
    {
        "id": "linkedin-001",
        "name": "Rachel Torres",
        "company": "Nexus Professional Services",
        "title": "Director of Strategy",
        "email": "r.torres@nexusps.com.au",
        "source": "linkedin",
        "industry": "professional_services",
        "company_size": 310,
        "is_authentic": True,
    },
    {
        "id": "linkedin-002",
        "name": "Mark Stevens",
        "company": "GreenField Agriculture",
        "title": "General Manager",
        "email": "mark.s@greenfield.com.au",
        "source": "linkedin",
        "industry": "agriculture",
        "company_size": 600,
        "is_authentic": True,
    },
    {
        "id": "linkedin-003",
        "name": "Sarah Chen",
        "company": "Meridian Health Group",
        "title": "Head of Digital Transformation",
        "email": "s.chen@meridianhealth.com.au",
        "source": "linkedin",
        "industry": "healthcare",
        "company_size": 450,
        "is_authentic": True,
    },
    {
        "id": "linkedin-004",
        "name": "Anika Patel",
        "company": "PayStream Fintech",
        "title": "Head of Product",
        "email": "anika@paystream.com.au",
        "source": "linkedin",
        "industry": "fintech",
        "company_size": 95,
        "is_authentic": True,
    },
    {
        "id": "linkedin-005",
        "name": "Ben Walker",
        "company": "TechVault Solutions",
        "title": "CEO",
        "email": "ben@techvault.com.au",
        "source": "linkedin",
        "industry": "saas",
        "company_size": 45,
        "is_authentic": True,
    },
    {
        "id": "linkedin-006",
        "name": "Suspicious Account",
        "company": "Quick Money LLC",
        "title": "Investor Relations",
        "email": "contact@quickmoney-invest.xyz",
        "source": "linkedin",
        "industry": "finance",
        "company_size": 3,
        "is_authentic": False,
    },
]

WEB_SCRAPE_LEADS = [
    {
        "id": "web-001",
        "name": "Laura Kim",
        "company": "HealthBridge Diagnostics",
        "title": "Director of Innovation",
        "email": "l.kim@healthbridge.com.au",
        "source": "web_scrape",
        "industry": "healthcare",
        "company_size": 280,
        "is_authentic": True,
    },
    {
        "id": "web-002",
        "name": "Chris O'Brien",
        "company": "EduTech Aus",
        "title": "Head of Curriculum Technology",
        "email": "cobrien@edutech.com.au",
        "source": "web_scrape",
        "industry": "education",
        "company_size": 150,
        "is_authentic": True,
    },
    {
        "id": "web-003",
        "name": "No Email Person",
        "company": "Mystery Corp",
        "title": "Manager",
        "email": "",
        "source": "web_scrape",
        "industry": "saas",
        "company_size": 200,
        "is_authentic": True,
    },
    {
        "id": "web-004",
        "name": "Olivia Nguyen",
        "company": "ScaleUp Advisory",
        "title": "Managing Partner",
        "email": "olivia@scaleup.com.au",
        "source": "web_scrape",
        "industry": "professional_services",
        "company_size": 55,
        "is_authentic": True,
    },
    {
        "id": "web-005",
        "name": "Ryan Mitchell",
        "company": "DataForge Analytics",
        "title": "CTO",
        "email": "ryan.m@dataforge.io",
        "source": "web_scrape",
        "industry": "saas",
        "company_size": 175,
        "is_authentic": True,
    },
    {
        "id": "web-006",
        "name": "Invalid Entry",
        "company": "",
        "title": "",
        "email": "noreply",
        "source": "web_scrape",
        "industry": "unknown",
        "company_size": 0,
        "is_authentic": False,
    },
]

REFERRAL_LEADS = [
    {
        "id": "ref-001",
        "name": "Emma Thompson",
        "company": "Apex Legal Partners",
        "title": "Head of Operations",
        "email": "e.thompson@apexlegal.com.au",
        "source": "referral",
        "industry": "professional_services",
        "company_size": 200,
        "is_authentic": True,
    },
    {
        "id": "ref-002",
        "name": "Alex Drummond",
        "company": "InsureTech Australia",
        "title": "VP of Claims Innovation",
        "email": "alex.d@insuretech.com.au",
        "source": "referral",
        "industry": "fintech",
        "company_size": 340,
        "is_authentic": True,
    },
    {
        "id": "ref-003",
        "name": "David Liu",
        "company": "CloudSync Solutions",
        "title": "VP Engineering",
        "email": "david.liu@cloudsync.io",
        "source": "referral",
        "industry": "saas",
        "company_size": 230,
        "is_authentic": True,
    },
    {
        "id": "ref-004",
        "name": "Nina Kowalski",
        "company": "BrightMind EdTech",
        "title": "CEO",
        "email": "nina@brightmind.edu.au",
        "source": "referral",
        "industry": "education",
        "company_size": 60,
        "is_authentic": True,
    },
    {
        "id": "ref-005",
        "name": "Liam Foster",
        "company": "FreshFoods Co-op",
        "title": "Director",
        "email": "liam@freshfoods.org.au",
        "source": "referral",
        "industry": "food_retail",
        "company_size": 30,
        "is_authentic": True,
    },
]
