PERSONAS = [
    {
        "persona_id": "persona-001",
        "name": "Friendly Fiona",
        "role": "Head of Operations",
        "company_type": "Mid-size healthcare provider",
        "personality_traits": ["collaborative", "open-minded", "detail-oriented"],
        "common_objections": ["Need to check with my team", "What's the implementation timeline?"],
        "buying_style": "amiable",
        "difficulty": "easy",
    },
    {
        "persona_id": "persona-002",
        "name": "Budget-Conscious Ben",
        "role": "CFO",
        "company_type": "Growing SaaS startup",
        "personality_traits": ["analytical", "cost-focused", "risk-averse"],
        "common_objections": ["That's above our budget", "Can you do it for less?", "What's the ROI timeline?"],
        "buying_style": "analytical",
        "difficulty": "easy",
    },
    {
        "persona_id": "persona-003",
        "name": "Technical Tara",
        "role": "CTO",
        "company_type": "Fintech scale-up",
        "personality_traits": ["technically rigorous", "data-driven", "skeptical of marketing claims"],
        "common_objections": ["How does this integrate with our stack?", "What about data security?", "Show me the architecture"],
        "buying_style": "analytical",
        "difficulty": "medium",
    },
    {
        "persona_id": "persona-004",
        "name": "Impatient Ivan",
        "role": "VP of Sales",
        "company_type": "Enterprise professional services",
        "personality_traits": ["results-driven", "impatient", "bottom-line focused"],
        "common_objections": ["We need this yesterday", "What's the fastest you can deliver?", "I don't have time for a long process"],
        "buying_style": "driver",
        "difficulty": "medium",
    },
    {
        "persona_id": "persona-005",
        "name": "Skeptical Steve",
        "role": "Managing Director",
        "company_type": "Traditional manufacturing firm",
        "personality_traits": ["skeptical of AI", "experienced", "values proven track record"],
        "common_objections": ["AI is just hype", "We tried something like this before and it failed", "Why should I trust your company?", "Our competitor does it cheaper"],
        "buying_style": "analytical",
        "difficulty": "hard",
    },
    {
        "persona_id": "persona-006",
        "name": "Political Patricia",
        "role": "Chief Strategy Officer",
        "company_type": "Large enterprise with complex stakeholder dynamics",
        "personality_traits": ["politically savvy", "non-committal", "consensus-seeking"],
        "common_objections": ["I need to socialise this with the board", "Our procurement process is very rigid", "Multiple departments need to sign off", "The timing isn't right"],
        "buying_style": "amiable",
        "difficulty": "hard",
    },
]
