SCENARIO_TEMPLATES = [
    {
        "scenario_id": "scenario-001",
        "title": "The Price Pushback",
        "description": "Prospect loves the product but their CFO thinks it's too expensive. You need to reframe the conversation around ROI.",
        "category": "negotiation",
        "difficulty": "medium",
        "conversation": [
            {"speaker": "prospect", "text": "Look, we really like what you've shown us, but 150K is a lot. Our CFO is pushing back hard on this.", "coaching_note": None},
            {"speaker": "rep", "text": "I understand budget is a key consideration. Can I ask what your team currently spends on the manual process this would replace?", "coaching_note": "Good - redirect to cost of inaction"},
            {"speaker": "prospect", "text": "Honestly I'm not sure of the exact number. Maybe 3 or 4 full-time people worth of effort.", "coaching_note": None},
            {"speaker": "rep", "text": "At average salary plus overhead, that's roughly 400 to 500K annually. Our solution would pay for itself within the first 4 to 5 months.", "coaching_note": "Quantify the savings to make the ROI tangible"},
            {"speaker": "prospect", "text": "That's a good point. I hadn't framed it that way. Let me take those numbers back to the CFO.", "coaching_note": None},
            {"speaker": "rep", "text": "Happy to join a call with your CFO to walk through the ROI model together. Sometimes it helps to have a third party present the analysis.", "coaching_note": "Offer to support the internal sale"},
        ],
        "ideal_outcome": "Prospect agrees to bring you into a meeting with the CFO to present the ROI case",
    },
    {
        "scenario_id": "scenario-002",
        "title": "The Competitor Comparison",
        "description": "Prospect is evaluating you against a cheaper competitor. You need to differentiate without badmouthing the competition.",
        "category": "objection_handling",
        "difficulty": "hard",
        "conversation": [
            {"speaker": "prospect", "text": "We've also been talking to TechRival and their solution is about 40% cheaper than yours. Why should we go with you?", "coaching_note": None},
            {"speaker": "rep", "text": "That's a fair question. Can I ask what criteria matter most to you beyond price? Is it reliability, support, integration depth?", "coaching_note": "Don't immediately defend price - understand their priorities first"},
            {"speaker": "prospect", "text": "Integration is big for us. We run a complex stack and we can't afford downtime during implementation.", "coaching_note": None},
            {"speaker": "rep", "text": "That's exactly where we differentiate. We include dedicated integration engineers and we've done 15 deployments in your industry. Can I share what one of those looked like?", "coaching_note": "Lead with proof points specific to their concern"},
            {"speaker": "prospect", "text": "Sure, but at the end of the day my boss is going to ask why we're paying more.", "coaching_note": None},
            {"speaker": "rep", "text": "Absolutely. The question I'd pose back is: what's the cost of a failed implementation? If the cheaper option takes twice as long or requires rework, the total cost of ownership flips.", "coaching_note": "Reframe from upfront cost to total cost of ownership"},
            {"speaker": "prospect", "text": "That's true. We had a bad implementation experience last year and it set us back months.", "coaching_note": None},
            {"speaker": "rep", "text": "Then you know the risk firsthand. I'd love to connect you with a reference customer who had a similar concern and can speak to the implementation experience.", "coaching_note": "Use social proof from peers to build confidence"},
        ],
        "ideal_outcome": "Prospect agrees to a reference call and acknowledges that total cost of ownership matters more than upfront price",
    },
    {
        "scenario_id": "scenario-003",
        "title": "The Hesitant First-Timer",
        "description": "Prospect has never used AI solutions before and is nervous about adopting new technology. Build confidence through education.",
        "category": "discovery",
        "difficulty": "easy",
        "conversation": [
            {"speaker": "prospect", "text": "I'll be honest, we've never used anything like this before. I'm not even sure our team would adopt it.", "coaching_note": None},
            {"speaker": "rep", "text": "That's actually really common. Most of our best customers started exactly where you are. What would it take for your team to feel comfortable with a new tool?", "coaching_note": "Normalise their concern and ask about adoption requirements"},
            {"speaker": "prospect", "text": "Probably seeing it work with minimal disruption. Our staff aren't very tech-savvy.", "coaching_note": None},
            {"speaker": "rep", "text": "That's why we include hands-on training and a dedicated success manager for the first 90 days. Would a small pilot with your most open-minded team members be a good starting point?", "coaching_note": "Reduce risk with a pilot and support commitment"},
            {"speaker": "prospect", "text": "A pilot sounds less scary than a full rollout. How long would that take?", "coaching_note": None},
            {"speaker": "rep", "text": "Typically 4 to 6 weeks for a pilot. We'd pick one workflow, automate it, measure the results, and your team can decide from there if they want to expand.", "coaching_note": "Be specific about pilot scope and timeline"},
        ],
        "ideal_outcome": "Prospect agrees to a pilot program with clear success criteria",
    },
    {
        "scenario_id": "scenario-004",
        "title": "The Stalled Deal",
        "description": "You had a great first call two weeks ago but the prospect has gone quiet. Re-engage without being pushy.",
        "category": "closing",
        "difficulty": "medium",
        "conversation": [
            {"speaker": "rep", "text": "Hi, just following up on our conversation from two weeks ago. I wanted to share a case study that's directly relevant to what you described.", "coaching_note": "Lead with value, not 'just checking in'"},
            {"speaker": "prospect", "text": "Oh right, sorry I've been swamped. Things have been hectic internally.", "coaching_note": None},
            {"speaker": "rep", "text": "No worries at all. I know how it gets. The case study shows how a similar company reduced their reporting time by 70%. Would that be useful context for your internal discussions?", "coaching_note": "Re-anchor the value proposition with concrete numbers"},
            {"speaker": "prospect", "text": "Actually yes, that would help. My manager has been asking about options and I haven't had time to put anything together for her.", "coaching_note": None},
            {"speaker": "rep", "text": "I can put together a one-page summary that you could forward directly. Would that save you some time?", "coaching_note": "Make it easy for the champion to sell internally"},
            {"speaker": "prospect", "text": "That would be amazing actually. If you can send that today I can get it in front of her this week.", "coaching_note": None},
        ],
        "ideal_outcome": "Prospect re-engages and you provide materials that enable them to champion the deal internally",
    },
    {
        "scenario_id": "scenario-005",
        "title": "The Technical Gatekeeper",
        "description": "The CTO is blocking the deal because they have concerns about security and integration. Win them over with technical credibility.",
        "category": "objection_handling",
        "difficulty": "hard",
        "conversation": [
            {"speaker": "prospect", "text": "Before we go any further, I need to understand your security posture. We handle sensitive financial data and can't take any risks.", "coaching_note": None},
            {"speaker": "rep", "text": "Absolutely, security is non-negotiable. We're SOC 2 Type II certified, encrypt all data at rest and in transit, and we can deploy within your VPC if required.", "coaching_note": "Lead with certifications and flexibility"},
            {"speaker": "prospect", "text": "VPC deployment is interesting. What about our existing API gateway? We use Kong and everything has to route through it.", "coaching_note": None},
            {"speaker": "rep", "text": "We've integrated with Kong before. Our API is REST-based with OAuth 2.0 and we support custom header injection for gateway compatibility. I can have our solutions architect walk you through the architecture.", "coaching_note": "Show specific technical knowledge, offer architect access"},
            {"speaker": "prospect", "text": "That would be helpful. I also want to understand your data retention and deletion policies.", "coaching_note": None},
            {"speaker": "rep", "text": "We follow APRA CPS 234 guidelines. Data retention is configurable per client and we support full data purge on contract termination with a certificate of destruction.", "coaching_note": "Reference specific regulatory frameworks they care about"},
            {"speaker": "prospect", "text": "Okay, that's thorough. Set up the architecture review and I'll bring my security lead.", "coaching_note": None},
        ],
        "ideal_outcome": "CTO agrees to architecture review and brings security team, signalling serious evaluation",
    },
    {
        "scenario_id": "scenario-006",
        "title": "The Budget Isn't Approved Yet",
        "description": "Prospect loves the solution but doesn't have budget allocated. Help them build the business case.",
        "category": "negotiation",
        "difficulty": "easy",
        "conversation": [
            {"speaker": "prospect", "text": "This all sounds great but honestly we don't have budget for this right now. It wasn't in our annual plan.", "coaching_note": None},
            {"speaker": "rep", "text": "I hear you. Many of our customers actually came to us mid-cycle because the pain became urgent. Is there a process for requesting unplanned budget at your company?", "coaching_note": "Explore their internal budget process"},
            {"speaker": "prospect", "text": "We can submit a business case to the executive team. They meet monthly to review discretionary spending.", "coaching_note": None},
            {"speaker": "rep", "text": "I can help you build that business case. We've got a template that maps out the cost of the current process versus the cost of our solution with projected savings. Would that be helpful?", "coaching_note": "Offer tangible support to make their job easier"},
            {"speaker": "prospect", "text": "That would actually be really helpful. The next exec meeting is in three weeks.", "coaching_note": None},
            {"speaker": "rep", "text": "Perfect. Let's work backwards from that date. I'll send the template today and we can refine it together this week so you're ready.", "coaching_note": "Create urgency with a deadline and offer partnership"},
        ],
        "ideal_outcome": "Prospect commits to submitting a business case with your help and a clear timeline",
    },
    {
        "scenario_id": "scenario-007",
        "title": "The Multi-Stakeholder Maze",
        "description": "Multiple decision makers with different priorities. Navigate the politics and build consensus.",
        "category": "discovery",
        "difficulty": "hard",
        "conversation": [
            {"speaker": "prospect", "text": "I like what I see but I should warn you, getting anything approved here involves our CEO, CFO, CTO, and the department heads. It's a process.", "coaching_note": None},
            {"speaker": "rep", "text": "I appreciate the heads up. It sounds like each of them probably cares about different things. Can you help me understand what matters most to each stakeholder?", "coaching_note": "Map the stakeholder landscape early"},
            {"speaker": "prospect", "text": "The CEO cares about growth and market position. CFO wants ROI numbers. CTO needs technical validation. And the department heads just want minimal disruption.", "coaching_note": None},
            {"speaker": "rep", "text": "That's really helpful. What if we structured the next steps as separate tailored conversations? A strategic overview for the CEO, an ROI deep-dive for the CFO, and a technical session for the CTO.", "coaching_note": "Customise the approach per stakeholder"},
            {"speaker": "prospect", "text": "That's smart. The CEO and CFO usually meet together, so you could do a combined session for them.", "coaching_note": None},
            {"speaker": "rep", "text": "Even better. And for the department heads, we could run a brief demo showing how the day-to-day workflow stays simple. Who would you say is the most influential voice in the room?", "coaching_note": "Identify the real decision maker"},
            {"speaker": "prospect", "text": "Honestly the CFO. If she's convinced on the numbers, the rest usually follow.", "coaching_note": None},
            {"speaker": "rep", "text": "Then let's make sure the CFO presentation is bulletproof. I'll prepare a custom ROI model using your actual volumes. Can you share some baseline numbers?", "coaching_note": "Focus energy on the key decision maker"},
        ],
        "ideal_outcome": "Prospect helps you map stakeholders and agrees to facilitate tailored meetings with each",
    },
    {
        "scenario_id": "scenario-008",
        "title": "The Renewal Upsell",
        "description": "Existing customer is up for renewal. Explore expansion opportunities while securing the renewal.",
        "category": "closing",
        "difficulty": "easy",
        "conversation": [
            {"speaker": "rep", "text": "Great to catch up. Your renewal is coming up next month. How has the platform been working for your team?", "coaching_note": "Start with satisfaction before discussing renewal"},
            {"speaker": "prospect", "text": "The team loves it honestly. The reporting automation alone has saved us about 20 hours a week.", "coaching_note": None},
            {"speaker": "rep", "text": "That's fantastic to hear. 20 hours a week is significant. Have you thought about applying similar automation to other workflows? I noticed your customer onboarding process might benefit.", "coaching_note": "Plant the upsell seed naturally based on observed opportunity"},
            {"speaker": "prospect", "text": "Funny you mention that. Our onboarding team has been asking if we can extend the platform to cover their processes too.", "coaching_note": None},
            {"speaker": "rep", "text": "Perfect timing then. We have an onboarding module that integrates directly with what you're already using. I could add it to the renewal proposal so you get the bundled pricing.", "coaching_note": "Bundle the upsell with renewal for better pricing optics"},
            {"speaker": "prospect", "text": "What kind of pricing difference are we talking about?", "coaching_note": None},
            {"speaker": "rep", "text": "Adding the onboarding module at renewal saves about 25% versus purchasing it separately later. Shall I put together a combined proposal?", "coaching_note": "Create urgency with renewal-specific discount"},
        ],
        "ideal_outcome": "Customer renews with expanded scope at bundled pricing",
    },
    {
        "scenario_id": "scenario-009",
        "title": "The AI Skeptic",
        "description": "Prospect has been burned by AI hype before and is deeply skeptical. Win trust through honesty and realism.",
        "category": "objection_handling",
        "difficulty": "hard",
        "conversation": [
            {"speaker": "prospect", "text": "I'll be blunt. We spent 200K on an AI project two years ago and it was a complete waste. I'm not keen to repeat that.", "coaching_note": None},
            {"speaker": "rep", "text": "I appreciate the honesty. Can you tell me what went wrong with that project? Understanding that would help me be straight with you about whether we can actually help.", "coaching_note": "Acknowledge the bad experience and show genuine curiosity"},
            {"speaker": "prospect", "text": "The vendor oversold what AI could do. The accuracy was terrible, our staff didn't trust the outputs, and we ended up going back to manual processes.", "coaching_note": None},
            {"speaker": "rep", "text": "That's a common story unfortunately. The truth is AI works really well for structured, repetitive tasks but it's not magic. We'd be honest about what it can and can't do for your specific use case.", "coaching_note": "Be honest about AI limitations - builds credibility"},
            {"speaker": "prospect", "text": "That's refreshing to hear at least. Most vendors just promise the moon.", "coaching_note": None},
            {"speaker": "rep", "text": "We'd rather under-promise and over-deliver. Would it help if we did a free proof of concept with your actual data? No commitment, and you'd see real results before spending a dollar.", "coaching_note": "Remove all risk with a free POC"},
            {"speaker": "prospect", "text": "A free proof of concept? What's the catch?", "coaching_note": None},
            {"speaker": "rep", "text": "No catch. It takes about two weeks. If the results aren't compelling, we shake hands and part ways. We only want customers who genuinely benefit.", "coaching_note": "Complete transparency builds trust with skeptics"},
        ],
        "ideal_outcome": "Skeptical prospect agrees to a no-commitment proof of concept",
    },
    {
        "scenario_id": "scenario-010",
        "title": "The Scope Creep Negotiation",
        "description": "During proposal review, the prospect keeps adding requirements without wanting to increase budget.",
        "category": "negotiation",
        "difficulty": "medium",
        "conversation": [
            {"speaker": "prospect", "text": "The proposal looks good but we'd also need it to integrate with our HR system and generate custom dashboards. Can you include that in the same price?", "coaching_note": None},
            {"speaker": "rep", "text": "Those are both great additions and we can definitely do them. Let me be transparent though, adding those features would increase the scope significantly. Can we talk about which of these is highest priority for the initial phase?", "coaching_note": "Acknowledge the request but set boundaries on scope"},
            {"speaker": "prospect", "text": "Ideally we'd want both. The HR integration is more urgent though.", "coaching_note": None},
            {"speaker": "rep", "text": "What if we include the HR integration in phase one at the current price, and scope the custom dashboards as a phase two add-on? That way you get the critical piece now without delaying the project.", "coaching_note": "Offer phased approach to protect scope while showing flexibility"},
            {"speaker": "prospect", "text": "Phase two would need to be at a fixed price though. We can't have open-ended costs.", "coaching_note": None},
            {"speaker": "rep", "text": "Absolutely, I can provide a fixed quote for phase two once we scope the dashboard requirements. Would a follow-up session with your reporting team help us nail down exactly what they need?", "coaching_note": "Agree to fixed pricing but ensure scope is properly defined first"},
        ],
        "ideal_outcome": "Prospect agrees to phased approach with HR integration in phase one and dashboards scoped separately",
    },
]
