from datetime import datetime, timezone

TRANSCRIPTS = {
    "call-001": {
        "call_id": "call-001",
        "rep_name": "Jordan Ellis",
        "prospect_name": "Sarah Chen",
        "prospect_company": "Meridian Health Group",
        "date": datetime(2026, 3, 15, 10, 0, tzinfo=timezone.utc),
        "duration_s": 1320,
        "segments": [
            {"speaker": "rep", "timestamp_s": 0, "text": "Hi Sarah, thanks for taking the time today. I'm Jordan from SimplAI. I understand you're looking at digital transformation options for Meridian Health?"},
            {"speaker": "prospect", "timestamp_s": 15, "text": "Yes, thanks Jordan. We've been exploring ways to streamline our patient intake and reporting workflows. Right now everything is very manual and it's slowing us down."},
            {"speaker": "rep", "timestamp_s": 35, "text": "That's a common pain point we hear in healthcare. Can you walk me through what the current workflow looks like day-to-day?"},
            {"speaker": "prospect", "timestamp_s": 50, "text": "Sure. Our front desk staff manually enters patient data from forms, then that gets re-entered into our reporting system. We have about 450 staff across six clinics and the duplication is costing us significant time."},
            {"speaker": "rep", "timestamp_s": 75, "text": "That sounds like a lot of redundant data handling. Have you quantified the time cost per clinic?"},
            {"speaker": "prospect", "timestamp_s": 90, "text": "Roughly 15 to 20 hours per week per clinic on just data re-entry. Our board is definitely interested in reducing that."},
            {"speaker": "rep", "timestamp_s": 105, "text": "That's substantial. We've worked with similar healthcare organisations to automate those handoffs. What's your timeline looking like for making a decision?"},
            {"speaker": "prospect", "timestamp_s": 120, "text": "We'd like to have something in place by Q3 this year. Budget has been approved in principle, we're looking at solutions in the 150 to 200K AUD range."},
            {"speaker": "rep", "timestamp_s": 140, "text": "That's great to hear there's budget alignment. Who else is involved in the decision-making process?"},
            {"speaker": "prospect", "timestamp_s": 155, "text": "Our CFO Michael needs to sign off, and our IT director Raj will evaluate the technical fit. I'm the business sponsor."},
            {"speaker": "rep", "timestamp_s": 170, "text": "Perfect. Would it make sense to set up a technical deep-dive with Raj next week? We can show how our automation pipeline handles the intake-to-reporting flow."},
            {"speaker": "prospect", "timestamp_s": 185, "text": "Yes, I think that would be really valuable. Raj is definitely interested in seeing how it integrates with our existing systems."},
            {"speaker": "rep", "timestamp_s": 200, "text": "Excellent. We've done similar integrations with HealthKit and MedConnect. I'll send over a case study from a similar deployment we did with a 300-person clinic group in Melbourne."},
            {"speaker": "prospect", "timestamp_s": 220, "text": "That would be great. I'm excited about the possibilities here. This could really free up our clinical staff to focus on patient care rather than paperwork."},
            {"speaker": "rep", "timestamp_s": 240, "text": "Absolutely, that's exactly the outcome we aim for. I'll follow up with calendar options for the technical session and that case study by end of day. Thanks Sarah."},
            {"speaker": "prospect", "timestamp_s": 255, "text": "Thanks Jordan, looking forward to it."},
        ],
    },
    "call-002": {
        "call_id": "call-002",
        "rep_name": "Jordan Ellis",
        "prospect_name": "Mark Stevens",
        "prospect_company": "GreenField Agriculture",
        "date": datetime(2026, 3, 18, 14, 30, tzinfo=timezone.utc),
        "duration_s": 1680,
        "segments": [
            {"speaker": "rep", "timestamp_s": 0, "text": "Hi Mark, Jordan here from SimplAI. Thanks for connecting on LinkedIn. You mentioned you were interested in how AI could help with your operations?"},
            {"speaker": "prospect", "timestamp_s": 12, "text": "Yeah, I saw your post about automation for mid-size businesses. We're a 600-person agriculture operation and honestly I'm a bit unsure about where AI fits for us."},
            {"speaker": "rep", "timestamp_s": 30, "text": "That's completely fair. AI isn't a silver bullet. Can you tell me about your biggest operational bottlenecks right now?"},
            {"speaker": "prospect", "timestamp_s": 45, "text": "Our main issue is supply chain coordination. We manage produce from 12 farms to distribution centres and the logistics planning is all spreadsheet-based. It's difficult to predict demand accurately."},
            {"speaker": "rep", "timestamp_s": 65, "text": "Demand forecasting is actually one of the strongest use cases for AI in agriculture. Are you currently using any forecasting tools?"},
            {"speaker": "prospect", "timestamp_s": 80, "text": "No, it's mostly gut feel and historical patterns our team tracks manually. We've looked at some tools but they seem expensive and I'm worried about the timeline to see results."},
            {"speaker": "rep", "timestamp_s": 100, "text": "What kind of budget range are you considering for this?"},
            {"speaker": "prospect", "timestamp_s": 110, "text": "That's the thing, we haven't really allocated a specific budget yet. The board is skeptical about AI spending in general. They keep asking why us versus competitor X who does it cheaper."},
            {"speaker": "rep", "timestamp_s": 130, "text": "That's a valid concern. The way we approach it is by starting with a focused pilot, maybe one farm-to-distribution route, to demonstrate measurable ROI before scaling."},
            {"speaker": "prospect", "timestamp_s": 150, "text": "A pilot could work, but I'm concerned about the cost even for that. We had a bad experience with a tech vendor last year who over-promised and under-delivered."},
            {"speaker": "rep", "timestamp_s": 170, "text": "I understand that concern. Would it help if I shared some references from similar agricultural businesses we've worked with? And we can structure the pilot with clear success metrics upfront."},
            {"speaker": "prospect", "timestamp_s": 190, "text": "Maybe. I need to discuss with my operations director first. She's the one who really feels the pain day-to-day. I'm not sure this is the right time for us honestly."},
            {"speaker": "rep", "timestamp_s": 210, "text": "No pressure at all, Mark. Would it be useful if I sent over a brief one-pager on what a pilot would look like specifically for agriculture supply chain? You could share it with your operations director."},
            {"speaker": "prospect", "timestamp_s": 230, "text": "Sure, that couldn't hurt. Send it through and I'll take a look when I get a chance."},
            {"speaker": "rep", "timestamp_s": 245, "text": "Will do. And if it makes sense to continue the conversation after that, we can set up a call with your operations director included. Thanks for your time Mark."},
            {"speaker": "prospect", "timestamp_s": 260, "text": "Thanks Jordan. I appreciate you not being too pushy about it."},
        ],
    },
    "call-003": {
        "call_id": "call-003",
        "rep_name": "Maya Rodriguez",
        "prospect_name": "James Worthington",
        "prospect_company": "FinEdge Capital",
        "date": datetime(2026, 3, 22, 9, 0, tzinfo=timezone.utc),
        "duration_s": 1500,
        "segments": [
            {"speaker": "rep", "timestamp_s": 0, "text": "Good morning James, Maya from SimplAI. We spoke briefly at the FinTech Melbourne event. You mentioned compliance reporting was eating up your team's time?"},
            {"speaker": "prospect", "timestamp_s": 15, "text": "Yes, that's right. We spend an enormous amount of time on regulatory compliance reports. Our team of 120 has about 8 people dedicated just to compliance documentation."},
            {"speaker": "rep", "timestamp_s": 30, "text": "Eight people on compliance alone is significant overhead. What does the current reporting workflow look like?"},
            {"speaker": "prospect", "timestamp_s": 45, "text": "We pull data from three different systems, consolidate it in Excel, cross-reference against regulatory requirements, then format the final reports. Each quarterly report takes about two weeks."},
            {"speaker": "rep", "timestamp_s": 65, "text": "Two weeks per quarter is a lot of manual work. We've built automation pipelines that can reduce that significantly. What would it mean for your business if that was down to two days?"},
            {"speaker": "prospect", "timestamp_s": 80, "text": "That would be transformative honestly. But I have to ask about the price. We've been quoted 300K from another vendor and our board thinks that's too expensive for compliance tooling."},
            {"speaker": "rep", "timestamp_s": 100, "text": "I understand price sensitivity. Our approach is modular, so you don't have to buy the full suite. We could start with just the data consolidation layer which handles the most time-consuming part."},
            {"speaker": "prospect", "timestamp_s": 120, "text": "What would that cost roughly?"},
            {"speaker": "rep", "timestamp_s": 125, "text": "For an organisation your size, the consolidation module typically runs between 80 to 120K AUD with implementation. That would likely save you 3 to 4 of those 8 headcount worth of compliance time."},
            {"speaker": "prospect", "timestamp_s": 145, "text": "That's more reasonable. The ROI story is interesting because we're paying those 8 people around 100K each. If we can redirect even half of them to higher-value work, it pays for itself."},
            {"speaker": "rep", "timestamp_s": 165, "text": "Exactly. And because it's fintech, we're SOC 2 compliant and have experience with APRA reporting requirements specifically."},
            {"speaker": "prospect", "timestamp_s": 180, "text": "That's good to know. APRA is exactly what we're dealing with. Can you send me a proposal with the modular pricing breakdown? I want to take it to our CFO."},
            {"speaker": "rep", "timestamp_s": 200, "text": "Absolutely. I'll have a tailored proposal to you by Thursday. Should I include reference contacts from other fintech clients?"},
            {"speaker": "prospect", "timestamp_s": 215, "text": "Yes please. Especially anyone in the lending or capital markets space, that would carry weight with our leadership."},
            {"speaker": "rep", "timestamp_s": 230, "text": "Perfect, I have two great references in exactly that space. I'll include them in the proposal. Thanks James, this has been a really productive conversation."},
            {"speaker": "prospect", "timestamp_s": 245, "text": "Agreed. Looking forward to the proposal Maya. Talk soon."},
        ],
    },
}
